from __future__ import annotations

from src.models import GeneratedProject, ProjectBlueprint


class CodeOrchestrator:
    def generate_project(self, blueprint: ProjectBlueprint) -> GeneratedProject:
        files = {
            "app/main.py": self._main_py(blueprint),
            "app/models.py": "from pydantic import BaseModel\n\nclass Item(BaseModel):\n    id: int\n    name: str\n",
            "tests/test_health.py": "def test_health():\n    assert True\n",
            "README.md": f"# {blueprint.name}\n\nGenerated by omni-nl-code.\n",
        }
        compose = (
            "version: '3.8'\nservices:\n"
            f"  {blueprint.name}:\n"
            "    build: .\n"
            "    ports:\n"
            "      - '8000:8000'\n"
        )
        lines = sum(len(v.splitlines()) for v in files.values())
        return GeneratedProject(
            blueprint=blueprint,
            files=files,
            total_files=len(files),
            total_lines=lines,
            readme=files["README.md"],
            docker_compose=compose,
        )

    @staticmethod
    def _main_py(blueprint: ProjectBlueprint) -> str:
        return (
            "from fastapi import FastAPI\n\n"
            "app = FastAPI()\n\n"
            "@app.get('/health')\n"
            "def health():\n"
            "    return {'status': 'ok'}\n"
        )
