#!/usr/bin/env bash
set -Eeuo pipefail

VERDACCIO_URL="${VERDACCIO_URL:-http://omni-verdaccio:4873}"
ADMIN_USER="${VERDACCIO_ADMIN_USER:-admin}"
ADMIN_EMAIL="${VERDACCIO_ADMIN_EMAIL:-admin@omni.local}"
ADMIN_PASSWORD="${VERDACCIO_ADMIN_PASSWORD:-changeme}"
CI_USER="${VERDACCIO_CI_USER:-woodpecker-ci}"
CI_EMAIL="${VERDACCIO_CI_EMAIL:-ci@omni.local}"
CI_PASSWORD="${VERDACCIO_CI_PASSWORD:-changeme-ci}"
VAULT_HINT_PATH="secret/data/verdaccio/ci-token"

for _ in $(seq 1 90); do
  if curl -fsS "$VERDACCIO_URL/-/ping" >/dev/null; then
    break
  fi
  sleep 2
done

mkdir -p /tmp/verdaccio-init && cd /tmp/verdaccio-init
npm set registry "$VERDACCIO_URL"

add_user_expect() {
  local u="$1" p="$2" e="$3"
  expect <<EOT
spawn npm adduser --registry $VERDACCIO_URL --auth-type=legacy
expect "Username:" { send "$u\r" }
expect "Password:" { send "$p\r" }
expect "Email:" { send "$e\r" }
expect eof
EOT
}

if command -v expect >/dev/null 2>&1; then
  add_user_expect "$ADMIN_USER" "$ADMIN_PASSWORD" "$ADMIN_EMAIL" || true
  add_user_expect "$CI_USER" "$CI_PASSWORD" "$CI_EMAIL" || true
else
  echo "[verdaccio-init] expect not installed; skipping interactive adduser"
fi

mkdir -p packages/sdk-common packages/sdk-orchestrator packages/eslint-config packages/prettier-config packages/tsconfig
for pkg in sdk-common sdk-orchestrator eslint-config prettier-config tsconfig; do
  cat > "packages/$pkg/package.json" <<JSON
{
  "name": "@omni/$pkg",
  "version": "0.1.0",
  "private": false,
  "description": "Omni shared package: $pkg"
}
JSON
  cat > "packages/$pkg/README.md" <<MD
# @omni/$pkg

Bootstrap package generated by verdaccio-init.
MD
done

cat > /tmp/verdaccio-init/woodpecker-release-notes.md <<'MD'
# Woodpecker npm publish flow

- Trigger on release tag `v*`
- Set `NPM_TOKEN` from Vault-backed secret
- `npm publish --registry http://omni-verdaccio:4873`
MD

echo "[verdaccio-init] store generated CI npm token in Vault path: ${VAULT_HINT_PATH}"
echo "[verdaccio-init] completed"
