#!/bin/bash
# ╔══════════════════════════════════════════════════════════════════════════════════════╗
# ║  CHANGELOG GENERATOR — Auto-generate from Git commits                              ║
# ║  OMNI QUANTUM ELITE v3.0                                                           ║
# ╚══════════════════════════════════════════════════════════════════════════════════════╝
set -euo pipefail

OUTPUT="${1:-CHANGELOG.md}"
REPO_URL="${REPO_URL:-https://github.com/your-org/omni-quantum-elite}"

echo "# Changelog" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "All notable changes to Omni Quantum Elite." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Get all tags sorted by version
TAGS=$(git tag -l "v*" --sort=-v:refname 2>/dev/null || echo "")

if [[ -z "$TAGS" ]]; then
    echo "## [Unreleased]" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    
    # Group commits by type
    for TYPE in feat fix docs refactor test chore; do
        COMMITS=$(git log --oneline --grep="^${TYPE}" 2>/dev/null || true)
        if [[ -n "$COMMITS" ]]; then
            case "$TYPE" in
                feat) echo "### Added" >> "$OUTPUT" ;;
                fix) echo "### Fixed" >> "$OUTPUT" ;;
                docs) echo "### Documentation" >> "$OUTPUT" ;;
                refactor) echo "### Changed" >> "$OUTPUT" ;;
                test) echo "### Testing" >> "$OUTPUT" ;;
                chore) echo "### Maintenance" >> "$OUTPUT" ;;
            esac
            echo "" >> "$OUTPUT"
            echo "$COMMITS" | while read -r line; do
                HASH=$(echo "$line" | cut -d' ' -f1)
                MSG=$(echo "$line" | cut -d' ' -f2-)
                echo "- ${MSG} ([${HASH}](${REPO_URL}/commit/${HASH}))" >> "$OUTPUT"
            done
            echo "" >> "$OUTPUT"
        fi
    done
else
    PREV_TAG=""
    for TAG in $TAGS; do
        echo "## [$TAG]" >> "$OUTPUT"
        
        # Get tag date
        TAG_DATE=$(git log -1 --format=%ai "$TAG" 2>/dev/null | cut -d' ' -f1)
        echo "*Released: $TAG_DATE*" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
        
        # Get commits between tags
        if [[ -n "$PREV_TAG" ]]; then
            RANGE="${TAG}..${PREV_TAG}"
        else
            RANGE="$TAG"
        fi
        
        # Group by type
        for TYPE in feat fix docs; do
            COMMITS=$(git log --oneline --grep="^${TYPE}" "$RANGE" 2>/dev/null || true)
            if [[ -n "$COMMITS" ]]; then
                case "$TYPE" in
                    feat) echo "### Added" >> "$OUTPUT" ;;
                    fix) echo "### Fixed" >> "$OUTPUT" ;;
                    docs) echo "### Documentation" >> "$OUTPUT" ;;
                esac
                echo "" >> "$OUTPUT"
                echo "$COMMITS" | while read -r line; do
                    MSG=$(echo "$line" | cut -d' ' -f2-)
                    echo "- ${MSG}" >> "$OUTPUT"
                done
                echo "" >> "$OUTPUT"
            fi
        done
        
        PREV_TAG="$TAG"
    done
fi

echo "---" >> "$OUTPUT"
echo "*Generated by Omni Quantum Elite Changelog Generator*" >> "$OUTPUT"

echo "Changelog generated: $OUTPUT"
